<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="desktop-linux-anh-le" name="web_drive.Topic_03_Xpath_Css" tests="6" failures="1" timestamp="09 Oct 2021 13:41:56 GMT" time="6.199" errors="0">
  <testcase name="TC_05_Regis_with_invalid_Cpass" time="0.468" classname="web_drive.Topic_03_Xpath_Css"/>
  <testcase name="TC_02_Regis_with_invalid_email" time="0.638" classname="web_drive.Topic_03_Xpath_Css"/>
  <testcase name="TC_01_ValidateCurrentUrl" time="3.121" classname="web_drive.Topic_03_Xpath_Css"/>
  <testcase name="TC_05_Regis_with_invalid_phone" time="0.779" classname="web_drive.Topic_03_Xpath_Css">
    <failure type="java.lang.AssertionError" message="expected [Số điện thoại phải từ 10-11 số.] but found [Vui lòng nhập con số]">
      <![CDATA[java.lang.AssertionError: expected [Số điện thoại phải từ 10-11 số.] but found [Vui lòng nhập con số]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at web_drive.Topic_03_Xpath_Css.TC_05_Regis_with_invalid_phone(Topic_03_Xpath_Css.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_05_Regis_with_invalid_phone -->
  <testcase name="TC_04_Regis_with_invalid_pass" time="0.574" classname="web_drive.Topic_03_Xpath_Css"/>
  <testcase name="TC_03_Regis_with_invalid_Cemail" time="0.619" classname="web_drive.Topic_03_Xpath_Css"/>
</testsuite> <!-- web_drive.Topic_03_Xpath_Css -->
